/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ImageCropper */

#ifndef _Included_ImageCropper
#define _Included_ImageCropper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ImageCropper
 * Method:    getRegion
 * Signature: ([I)Ljava/awt/Rectangle;
 */
JNIEXPORT jobject JNICALL Java_ImageCropper_getRegion
  (JNIEnv *, jclass, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
